### ISSUE TITLE
外れ値検出について

### ISSUE THREAD

**Issue by ITOMIZUKI** [jjj999/fte-can09#2]
センサ値の取得に当たって、外れ値の検出、除外をする場合はどのクラスで行われることになりますか？

**Comment by jjj999** [comment]
現時点では外れ値の検出について特別用意しているクラスはありません．理由はセンサによっては値が急変しても不自然ではないものも存在するからです（例えば加速度センサ）．なので現在の状況では，フィルターが必要なのであれば開発者が実装しなくてはならない状況です．もし要望があれば，pisat 側に簡単なフィルター機能を実装することも検討します．

**Comment by ITOMIZUKI** [comment]
了解しました. 現在, 高度測定に対するフィルタリングを考えていました.
今回はNode側で実装を試そうと思います.

**Comment by jjj999** [comment]
了解です．
